
INSERT INTO `address` (`street_name`, `street_nb`, `city`, `province`, `zip_code`, `country`) VALUES
( '4147    55e rue Montréal Québec H1Z1E8', 4147, 'Montreal', 'quebec', 'H1Z1E8', 'Canada'),
( '4147    55e rue Montréal Québec H1Z1E8', 4147, 'Montreal', 'quebec', 'H1Z1E8', 'Canada');



INSERT INTO `product` ( `name`, `quantity`, `price`, `img_url`, `description`) VALUES
('wtyukilop;^èp', 4894, 999.99, '7979878', 'dsvbfngm,hj.hk'),
('Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612.\r\nCe livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12.\r\nLes différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
('Centré sur Dieu', 1, 12.00, '41klCoeJ9xL-225x300.jpg', 'Centré sur Dieu est un livre écrit par Zacharias Tanee Fomum, un pasteur et écrivain camerounais. Il s’agit d’un appel à revenir à la théologie biblique où Dieu occupe la place centrale dans la vie du croyant et de l’église. Le livre contient des enseignements basés sur la Genèse et d’autres passages de la Bible, ainsi que des témoignages personnels de l’auteur. Le livre a été publié en 2017 '),
('Aucun échec n\'a beso', 1, 8.00, 'aucun-echec-n-a-besoin-d-etre-final-1-1-150x200.jpg', 'Ce livre est le sixième tome d’une série intitulée Hors-Série, qui contient des messages de réveil et de restauration pour les croyants né de nouveau en Jésus-Christ. Le livre aborde le thème de la persévérance face aux épreuves et aux échecs, en affirmant que Dieu est toujours prêt à ramener ses enfants dans l’assurance en leur faisant oublier leur passé sombre et en leur donnant une nouvelle vie'),
('Combat pratique', 1, 15.00, 'Combat-pratique-1-150x200.jpg', ' Le livre traite de la lutte spirituelle du croyant contre les forces du mal, et propose des principes et des stratégies pour remporter la victoire. Le livre est basé sur les enseignements de la Bible et sur l’expérience personnelle de l’auteur. Il s’adresse à tous ceux qui veulent vivre une vie chrétienne victorieuse et témoigner de l’amour de Dieu dans le monde.'),
( 'La delivrance', 1, 14.00, 'Delivrance-1-1-150x200.jpg', 'Ce livre est une compilation de messages que l’auteur a donnés sur la délivrance de l’emprise des démons et des mauvais esprits. Il se base sur les Écritures pour montrer que la délivrance est possible grâce à la victoire du Seigneur Jésus sur la croix. Il propose aussi des conseils pratiques pour discerner la présence des démons, entreprendre la délivrance, et démarrer un ministère de délivrance.'),
( 'La célébrité', 1, 20.00, 'La-Celebrite-un-Masque-1-1-150x200.jpg', 'La Célébrité : Un Masque est le dernier livre que le Professeur Fomun avait écrit de sa propre main, après presque 56 ans dans la foi et plus de 35 ans de ministère au Cameroun et à l’international1.\r\nLe livre s’appuie sur l’histoire du général Naaman qui cachait sa lèpre et la couvrait avec le masque du succès militaire, de l’argent, de l’honneur, de la célébrité et des choses semblables2345.\r\nLe livre exprime le fardeau pesant que l’auteur avait de voir les âmes sauvées et fait ressortir le fait que la majorité des gens portent des masques pour tromper ou rendre la réalité confuse2345.\r\nLe livre invite les lecteurs à admettre leur péché, à recevoir le pardon de Jésus-Christ et à s’abandonner au Seigneur'),
( 'La centralité', 1, 25.00, 'La-Centralite-de-la-Priere-1-225x300.jpg', 'Le livre La Centralité de la Prière est un ouvrage chrétien écrit par Zacharias Tanee Fomum, un pasteur et professeur camerounais. Il s’agit d’une compilation des messages qu’il a donnés lors d’une session de l’Université Mondiale de la Prière, à Yaoundé, en août 2007. Le livre traite de l’importance de la prière dans la vie spirituelle, le ministère, et la mission chrétienne. Il exhorte les lecteurs à donner la priorité à la prière et à expérimenter la puissance de Dieu.'),
( 'La conscience du cro', 1, 30.00, 'La-Conscience-du-Croyant-150x200.jpg', 'Le livre La Conscience du Croyant de Zacharias Tanee Fomum est un ouvrage qui traite de l’état de la conscience des croyants chrétiens et de la façon dont ils peuvent coopérer avec Dieu pour avoir une conscience claire et pleine du Saint-Esprit. Le livre explique les différents états de la conscience, tels que le péché, la désobéissance, l’endurcissement, l’impureté, la conscience souillée, la conscience obscurcie et flétrie, et comment ils affectent la relation avec Dieu et les autres. Le livre propose également des moyens pratiques pour purifier et renforcer la conscience du croyant, tels que le repentir, la prière, le jeûne, le travail intègre, le partage du message de l’évangile, etc.'),
( 'l\'utilisation du tem', 1, 7.00, 'L\'utilisation-du-Temps-1-1-150x200.jpg', 'Le livre de L’utilisation-du-Temps de Zacharias Tanee Fomum est un guide spirituel pour les chrétiens qui veulent utiliser leur temps de manière efficace et glorieuse pour Dieu. L’auteur, qui était un évangéliste et un enseignant camerounais, explique comment le temps est un don précieux de Dieu et comment le gérer selon sa volonté. Il donne des conseils pratiques pour organiser son emploi du temps, établir des priorités, éviter les distractions, et profiter de chaque moment. Il souligne aussi l’importance de la prière, de la méditation, du jeûne, et de la communion avec Dieu comme des moyens de renouveler sa force et sa vision. Le livre est destiné à encourager et à inspirer les lecteurs à vivre une vie pleine de sens et de joie pour la gloire de Dieu.'),
( 'le péché de la pares', 1, 20.00, 'Peche-de-la-paresse-1-225x300.jpg', 'Le livre Peche-de-la-paresse de Zacharias tanee fonum est un ouvrage chrétien qui traite du problème de la paresse spirituelle et de ses conséquences. L’auteur, propose des solutions pratiques pour se délivrer de la paresse et vivre une vie pleine de zèle et de fruit pour Dieu.\r\n\r\nVoici un résumé du livre  \r\nQu’est-ce que la paresse? Quelles sont ses causes et ses manifestations? Quelles sont ses conséquences et les moyens d’en être délivré? Ce livre du professeur Z.T. Fomum te permettra de trouver des réponses à ces interrogations, mais bien plus à atteindre tout le potentiel que Dieu t’a donné, afin de le mettre à la disposition du royaume de Dieu. Cet ouvrage est un message fort à tout paresseux qui ne sera plus paresseux après la lecture et l’obéissance à son contenu.'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 1, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple'),
( 'Disciple coûte que c', 2, 10.00, '41fwuBEiDL._SX326_BO1204203200_-1-150x200.jpg', 'Disciple coûte que coûte est le premier livre écrit par le professeur Zacharias Tanee Fomum, un auteur chrétien et un professeur de chimie organique, en 197612. Ce livre reflète la pensée originale de l’auteur, qui affirme que le message fondamental du professeur Fomum n’a pas changé : la puissance du tout d’un homme12. Les différents thèmes abordés dans ce livre sont : le prix à payer pour être disciple, les fondements de la vie du disciple, le dessein de la vie du disciple, la souffrance du disciple, et la récompense du disciple');


INSERT INTO `user` ( `user_name`, `email`, `pwd`, `fname`, `lname`, `billing_address_id`, `shipping_address_id`, `token`, `role_id`) VALUES
('keyliah', 'keyliahfaith@gmail.com', 'c257202210cf9a2a1a1ffb6edb3b2d3e201d6299', 'nguekep', 'faith', 0, 0, '', 2),
('Ulrich', 'ulrichnguekep2@gmail.com', '0114e34ebadf7330e2698dd7591f84ee33f80596', 'ulrich Darly', 'Tchachoua Nguekep', 0, 0, '', 3),
('admin', 'admin@gmail.com', '28402d78183aa23e3b450bccbf2de9e4244caa5d', 'admin', 'admin', 0, 0, '', 1),
('eliel', 'elieljean@admin.com', '28402d78183aa23e3b450bccbf2de9e4244caa5d', 'Jean', 'Pascal', 0, 0, '', 2),
('ivine', 'ivine@gmail.com', 'b7b700cb128c9ded413439f99e7081925bf13c2b', 'cabrelle', 'laRonde', 0, 0, '', 3),
('lourdy', 'lourdy@gmail.com', '22030c692500f5327b4ed10a4c6a292fff713add', 'vanilla', 'acalia', 0, 0, '', 3),
('diane', 'uwera@gmail.com', 'b7b700cb128c9ded413439f99e7081925bf13c2b', 'diane', 'uwera', 0, 0, '', 3),
( 'Doriane', 'doriane@gmail.com', 'b7b700cb128c9ded413439f99e7081925bf13c2b', 'Nikiema', 'josé', 0, 0, '', 3),
( 'admin2', 'admin2@gmail.com', 'b7b700cb128c9ded413439f99e7081925bf13c2b', 'vanilla', 'vanillaAdmin2', 0, 0, '', 3),
( 'superadmin', 'superadmin@admin.ca', '28402d78183aa23e3b450bccbf2de9e4244caa5d', 'super', 'admin', 0, 0, '', 1),
( 'Junior', 'juniorwelle@test.com', 'b7b700cb128c9ded413439f99e7081925bf13c2b', 'EssoZollam', 'oceanne', 0, 0, '', 3),
( 'admin3', 'admin3@gmail.com', '28402d78183aa23e3b450bccbf2de9e4244caa5d', 'super', 'admin', 0, 0, '', 3);

-- --------------------------------------------------------
